# Generated by Django 5.0.4 on 2024-04-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='emailorphone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
