# Generated by Django 5.0.4 on 2024-04-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_signupdata_emailorphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdata',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/UserProfile'),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='emailorphone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
