# Generated by Django 5.0.4 on 2024-04-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_signupdata_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdata',
            name='confirm_password',
        ),
    ]
