# Generated by Django 5.0.4 on 2024-04-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_signupdata_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='image',
            field=models.ImageField(blank=True, upload_to='Media/'),
        ),
    ]
