# Generated by Django 5.0.4 on 2024-04-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_mencategory_menproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='image',
            field=models.ImageField(blank=True, upload_to='UpdateProfile/'),
        ),
    ]
