# Generated by Django 5.0.4 on 2024-04-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_signupdata_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mencategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='menproduct',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
