# Generated by Django 5.0.4 on 2024-04-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_rename_mencategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
