# Generated by Django 5.0.4 on 2024-04-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
