# Generated by Django 5.0.4 on 2024-04-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
