# Generated by Django 5.0.4 on 2024-04-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
