# Generated by Django 5.0.4 on 2024-04-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_trendycategory_trendyproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendyproduct',
            name='category',
        ),
        migrations.DeleteModel(
            name='TrendyCategory',
        ),
    ]
