# Generated by Django 5.0.4 on 2024-04-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_remove_trendyproduct_category_delete_trendycategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendyproduct',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='trendyproduct',
            name='image2',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='trendyproduct',
            name='image3',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='trendyproduct',
            name='image4',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='trendyproduct',
            name='image5',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='trendyproduct',
            name='image6',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
    ]
