# Generated by Django 5.0.4 on 2024-04-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_rename_image_trendyproduct_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Violet', 'Violet'), ('Black', 'Black'), ('Cream', 'Cream')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='trendyproduct',
            name='colors',
            field=models.ManyToManyField(to='application.color'),
        ),
    ]
