# Generated by Django 5.0.4 on 2024-04-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_color_trendyproduct_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendyproduct',
            name='colors',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
