# Generated by Django 5.0.4 on 2024-04-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_remove_trendyproduct_colors_delete_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='trendyproduct',
            name='colors',
            field=models.ManyToManyField(blank=True, to='application.color'),
        ),
    ]
