# Generated by Django 5.0.4 on 2024-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_color_trendyproduct_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menproduct',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='womenproduct',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='menproduct',
            name='colors',
            field=models.ManyToManyField(blank=True, to='application.color'),
        ),
        migrations.AddField(
            model_name='menproduct',
            name='image2',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='menproduct',
            name='image3',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='menproduct',
            name='image4',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='menproduct',
            name='image5',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='menproduct',
            name='image6',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='colors',
            field=models.ManyToManyField(blank=True, to='application.color'),
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='image2',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='image3',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='image4',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='image5',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='image6',
            field=models.ImageField(default='', upload_to='Product/'),
        ),
    ]
