# Generated by Django 5.0.4 on 2024-04-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_rename_image_menproduct_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KidsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('image1', models.ImageField(upload_to='Product/')),
                ('image2', models.ImageField(default='', upload_to='Product/')),
                ('image3', models.ImageField(default='', upload_to='Product/')),
                ('image4', models.ImageField(default='', upload_to='Product/')),
                ('image5', models.ImageField(default='', upload_to='Product/')),
                ('image6', models.ImageField(default='', upload_to='Product/')),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.kidscategory')),
                ('colors', models.ManyToManyField(blank=True, to='application.color')),
            ],
        ),
    ]
