# Generated by Django 5.0.4 on 2024-04-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_kidscategory_kidsproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidsproduct',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
