# Generated by Django 5.0.4 on 2024-04-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_kidsproduct_unique_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='menproduct',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trendyproduct',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
