# Generated by Django 5.0.4 on 2024-04-27 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_menproduct_unique_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('image1', models.ImageField(upload_to='Product/')),
                ('image2', models.ImageField(default='', upload_to='Product/')),
                ('image3', models.ImageField(default='', upload_to='Product/')),
                ('image4', models.ImageField(default='', upload_to='Product/')),
                ('image5', models.ImageField(default='', upload_to='Product/')),
                ('image6', models.ImageField(default='', upload_to='Product/')),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unique_identifier', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('colors', models.ManyToManyField(blank=True, to='application.color')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.maincategory')),
            ],
        ),
    ]
