# Generated by Django 5.0.4 on 2024-04-27 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_maincategory_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='unique_identifier',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image1', models.ImageField(upload_to='Product/')),
                ('image2', models.ImageField(default='', upload_to='Product/')),
                ('image3', models.ImageField(default='', upload_to='Product/')),
                ('image4', models.ImageField(default='', upload_to='Product/')),
                ('image5', models.ImageField(default='', upload_to='Product/')),
                ('image6', models.ImageField(default='', upload_to='Product/')),
                ('unique_identifier', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('colors', models.ManyToManyField(blank=True, to='application.color')),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.maincategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.subcategory')),
            ],
        ),
    ]
