# Generated by Django 5.0.4 on 2024-04-27 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_remove_subcategory_colors_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenCategory',
            new_name='PriceRange',
        ),
        migrations.RemoveField(
            model_name='kidsproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='kidsproduct',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='menproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menproduct',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='womenproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='womenproduct',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='pricerange',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.pricerange'),
        ),
        migrations.AddField(
            model_name='trendyproduct',
            name='pricerange',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.pricerange'),
        ),
        migrations.DeleteModel(
            name='KidsCategory',
        ),
        migrations.DeleteModel(
            name='KidsProduct',
        ),
        migrations.DeleteModel(
            name='MenProduct',
        ),
        migrations.DeleteModel(
            name='WomenCategory',
        ),
        migrations.DeleteModel(
            name='WomenProduct',
        ),
    ]
