# Generated by Django 5.0.4 on 2024-04-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_alter_product_pricerange_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pricerange',
        ),
        migrations.RemoveField(
            model_name='trendyproduct',
            name='pricerange',
        ),
    ]
