# Generated by Django 5.0.4 on 2024-04-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_remove_product_pricerange_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceRange',
        ),
    ]
