# Generated by Django 5.0.4 on 2024-04-27 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_delete_pricerange'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pricerange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.pricerange'),
        ),
        migrations.AddField(
            model_name='trendyproduct',
            name='pricerange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.pricerange'),
        ),
    ]
