# Generated by Django 5.0.4 on 2024-04-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_pricerange_product_pricerange_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='trendyproduct',
            name='pricerange',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='application.productsize'),
        ),
        migrations.AddField(
            model_name='trendyproduct',
            name='size',
            field=models.ManyToManyField(blank=True, to='application.productsize'),
        ),
    ]
