# Generated by Django 5.0.4 on 2024-04-29 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_productsize_remove_trendyproduct_pricerange_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendyProduct',
        ),
    ]
